### ISSUE TITLE
Installation of libcpplog

### ISSUE THREAD

**Issue by senshu** [doe300/VC4C#5]
`make install` does not install `libcpplog`

I had to manually run `sudo make install` from `build/build/cpplog`.
I also observed that `libcpplog` is not installed in the `CMAKE_INSTALL_PREFIX` that I set when running `cmake`.

**Comment by doe300** [comment]
Thanks for reporting.

This issue exists due to the fact that in VC4C's `CMakeLists.txt` the install target for `libcpplog` is skipped on purpose (lines 104/105).
The reason for this was CMake failing to create a configuration with two targets named install (one from `libcpplog`, one from `VC4C`).

In the latest commit, `libcpplog` is linked in statically intl `libVC4CC` (which I think makes more sense) circumventing this issue.
